version: "3.9"
service : 
client:
image: mhart/alpine-node:6.8.0
restart: always
ports : 
-"3000:3000"
working_dir: /client/src/app
entrypoint : ["npm","start"];

links: 
-api
networks:
  -webAppnetwork

  api: 
  image : webapp-api
  restart:always
  port: 
  -"9000:9000"
  volumes:
  -/api:/api
  -/api/node_moduless
  depends_on: 
  - mongodb
  networks: 
  -webappnetwork

  mongobd:
  image: mongo
  restart: always
  container_name: mongodb
  volumes:
    -./data-node:/data/db
    ports: -27017:27017
    command:
    mongod --noauth --smallfiles
    networks:
    -webappnetwork
    networks: 
    webappnetwork
    driver:bridge
    


